# Generated by Django 3.0.8 on 2020-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommate_details',
            name='food_preference',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('strictly veg', 'Strictly Veg'), ('strictly non veg', 'Strictly Non Veg')], default='Flexible', max_length=20),
            preserve_default=False,
        ),
    ]
